all:
  hosts:
    localhost:
      ansible_connection: local

  children:
    linux_machines:
      hosts:
        localhost:
          ansible_connection: local
        msi-fedora:
          ansible_host: 100.81.19.55
          ansible_user: hdh
          ansible_connection: ssh
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        hp-fedora:
          ansible_host: 100.113.69.26
          ansible_user: hdh
          ansible_connection: ssh
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519

    windows_machines:
      hosts:
        hlenovo:
          ansible_host: 100.99.207.31
          ansible_user: HDH
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_port: 5985
